### ISSUE TITLE
Content translation breaks derivatives

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#985] opened 2018-12-04 16:10 UTC
Reported by @kanasznagyzoltan

Part of https://github.com/Islandora-CLAW/CLAW/issues/939

After enabling content translation and the hungarian language, the language is being added to the url for files, which are unresolvable.  E.g. `http://localhost:8000/_flysystem/fedora/2018-12/image.png` is getting written out as `http://localhost:8000/hu/_flysystem/fedora/2018-12/image.png`, which does not exist.  This bogus url is getting onto the queue and being used as the `Apix-Ldp-Resource` header in derivative calls, and things are failing.

We generate the url here: https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/src/EventGenerator/EventGenerator.php#L25.  Should be pretty easy to isolate and change or way of making that url.

**Comment by Natkeeran** [comment] 2019-01-14 20:05
@dannylamb  

I reviewed this ticket.  Need clarification with respect to the right/expected behaviour.

For nodes, the user has the option to specify the language (example English or Hungarian) when creating the node.  However, for media, that option does not exist.  Should it exist?  I assume it should exist since media can be translated. 

If media can be translated, then if the user in a specific language node (i.e `http://localhost:8000/hu/node/1`), then when the user clicks to add media, should the media node that language?  This question can be resolved by adding the language field to the media.

If the language field exists, then that can help us specifying the right url.

**Comment by dannylamb** [comment] 2019-01-16 14:11
@kanasznagyzoltan Does adding the language field and setting it to Hungarian on the media work for you?

**Comment by DonRichards** [comment] 2019-01-16 19:09
I'm guessing but `json_encode($event, JSON_UNESCAPED_UNICODE)` on [EventGenerator.php#L102](https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/src/EventGenerator/EventGenerator.php#L102) and see what happens.

**Comment by rangel35** [comment] 2019-05-15 17:25
I had this same issue happen, I solved it by editing the configuration 
 Administration->Configuration->Regional and language->Languages->Detection and selection

and enabled session instead of domain, and it just adds a suffix ?lang=es 

lang can be language, you configure and choose the argument yourself

**Comment by dannylamb** [comment] 2019-05-15 18:11
@kanasznagyzoltan @Natkeeran ^^

Would that work for you?

**Comment by rangel35** [comment] 2019-05-15 20:38
@dannylamb @Natkeeran @kanasznagyzoltan

that might not work...we are having intermittent issues with it...It was working and now 3 before a local release it decides it no longer wants to work with the multilingual pages...from what Brandon can see on the back end it is adding extra content to the url so that it won't resolve the page...gives a 404 on the object tilesource   (not sure if you can read what the black box says but here is a screenshot)
![Screen Shot 2019-05-15 at 3 36 48 PM](https://user-images.githubusercontent.com/4051547/57807769-72810a00-7727-11e9-9df9-ab3043b83ea4.png)

**Comment by rangel35** [comment] 2019-05-15 21:05
deleted earlier comment about intermittent issues...that was strictly a permissions thing on our end so back to that works for me :)

**Comment by Natkeeran** [comment] 2019-05-17 14:09
@dannylamb 

The workaround does address the issue.  However, that won't be an appropriate solution for many use cases.  

"Language from the URL (Path prefix or domain)." is the default and one of the most common way to determine language.  If you don't have path url, there is no way to get a specific language url of a node or content.

Islandora 8 is definitely breaking some standard Drupal behaviour.  

Not addressing the core issue can be problematic down the line as well.

**Comment by Natkeeran** [comment] 2019-05-17 14:20
Just want to highlight that the issue is related to the storage of Original Files, which get stored to Fedora.  The service files, thumb nails etc that get stored to local file systems work fine.

**Closed** 2019-05-23 19:30 UTC
Labels: bug, drupal, multilingual
