### ISSUE TITLE
should all changes be indexed into the triplestore?

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#1139] opened 2019-06-02 15:22 UTC
Each time a field is edited, it creates a new triple in the triplestore (regardless of if revision is selected or not).  Is that the expected behaviour? 

I would expect only the triple from the current canonical representation to be in the triplestore.

**Comment by dannylamb** [comment] 2019-06-03 13:18
@Natkeerad I'm experiencing this too.  It's not expected behaviour.  We're confusing Alpaca here: https://github.com/Islandora-CLAW/Alpaca/blob/master/islandora-indexing-triplestore/src/main/java/ca/islandora/alpaca/indexing/triplestore/TriplestoreIndexer.java#L63

That's because we're declaring the ?_format=jsonld url as the subject before processing, but that is no longer the case.  Nodes no longer have ?_format=jsonld and media have a subject url of the file they describe.

**Comment by dannylamb** [comment] 2019-06-05 15:35
Resolved in 1.0.0

**Closed by dannylamb** 2019-06-05 15:35 UTC
Labels: Linked Data
