### ISSUE TITLE
Install controlled_access_terms and islandora_demo with claw-playbook

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#907] opened 2018-08-23 16:17 UTC
Now that these are their own github repos and have their own packge in packagist, pull these down using composer and enable them in claw-playbook. There's some whackiness with islandora_demo and content translation, so we _do not_ enable it with the other modules.  Instead it's done as a post-processing step.

TL;DR As long as you pull in both modules with composer [here](https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L6), enable controlled_access_terms [here](https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L27), and rename `islandora_demo_feature` to `islandora_demo` [here](https://github.com/Islandora-Devops/claw-playbook/blob/master/post-install.yml#L7), it should all play out.

**Comment by ppound** [comment] 2018-08-23 19:16
I've made the changes requested and I think it does what we need.  The controlled_access_terms module and the islandora_demo module are both installed and enabled after running the updated playbook.  There is a pull request here https://github.com/Islandora-Devops/claw-playbook/pull/75

There is still an islandora_demo_feature module in Drupal after running the playbook but it is not enabled, the demo feature is a submodule of the islandora module and can probably be removed at some point 

I ran into an issue adding taxonomy terms to media after doing a clean build but that maybe caused by updates to other modules?

**Comment by dannylamb** [comment] 2018-08-24 12:35
@ppound I'm spinning it up now to test.

**Comment by ppound** [comment] 2018-08-24 18:45
@dannylamb I Added the two requested pull requests to address the taxonomy on related media issue.  I May need some guidance on the best way to reload config to properly test the changes.

**Comment by whikloj** [comment] 2018-08-28 20:16
Resolved with https://github.com/Islandora-Devops/claw-playbook/commit/48e157a70528816b3e9adb57f43c83c9e828a496

**Closed by whikloj** 2018-08-28 20:16 UTC
Labels: Ansible, Small, migration
