### ISSUE TITLE
claw-playbook - Fedora fails to come up

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#757] opened 2017-11-22 21:12 UTC
With [latest](https://github.com/Islandora-Devops/claw-playbook/tree/4dd61e4e20cf5d5ff23a207cd1190d18f4912274) updates/merges, the Fedora fails to come up.  There are exceptions in the Tomcat log.  Log is attached.  

@whikloj @dannylamb 

[catalina.out.txt](https://github.com/Islandora-CLAW/CLAW/files/1497485/catalina.out.txt)

**Comment by MarcusBarnes** [comment] 2017-11-22 21:36
I can confirm @Natkeeran observation.  We both have the following message in our catalina log:

``SEVERE: Context [/fcrepo] startup failed due to previous errors``.

**Comment by whikloj** [comment] 2017-11-23 14:30
Ok I think I got this, just testing once more and I'll open a simple one line PR. Not sure why this start to fail after we merged the PRs in the main branch...

**Comment by whikloj** [comment] 2017-11-23 15:55
@dannylamb I have a fix for this, but also now we need to cut a new release for Alpaca to get all the changes. I don't know how to do that but am willing to try if you could provide some assistance. We should probably document how to release it...I've seen other projects add that right to the README.

**Comment by dannylamb** [comment] 2017-11-23 16:39
@whikloj It's buried in the Alpaca wiki: https://github.com/Islandora-CLAW/Alpaca/wiki/Alpaca-Release-Process
I'm :+1: to moving that into the README.

**Comment by dannylamb** [comment] 2017-11-23 19:57
Auto-closed due to keywords in PR, but I'm re-opening until we confirm that everything's a-okay after the Alpaca release and https://github.com/Islandora-Devops/claw-playbook/pull/34

**Comment by dannylamb** [comment] 2017-11-24 18:38
@whikloj @Natkeeran are we good to close this now?

**Comment by whikloj** [comment] 2017-11-24 18:48
Yes, this problem is resolved. We need a second PR to fix the Crayfish config, I'll open that now.

**Comment by Natkeeran** [comment] 2017-11-27 16:49
@whikloj Looks good to me.

**Closed** 2017-11-28 19:08 UTC
