### ISSUE TITLE
Reloading islandora_image form replaces the OBJ field

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#664] opened 2017-06-14 15:38 UTC
# Steps to reproduce
* Go to Add Content and create an Islandora Image node `http://localhost:8000/node/add/islandora_image`
* Enter the title
* Reload the page
* Click Add new media for OBJ
* (OBJ field seems to disappear)

The above steps consistently reproduces the issue.  

* Seems like a more basic problem.  When trying to create media for OBJ, it fails with the message "Only files with the following extensions are allowed: jp2."

I have the following committ:
```
commit 20ce269ae52b215a0eb7b673bddbd0833a610d69
Author: Nick Ruest <ruestn@gmail.com>
Date:   Tue Jun 13 09:24:29 2017 -0400
```

# Expected behavior
* Should allow the user to enter the OBJ.

## The actual, incorrect behavior
* OBJ field seems to disappear.

**Comment by Natkeeran** [comment] 2017-06-14 15:46
![islandora_image_obj_issue](https://user-images.githubusercontent.com/1827166/27141776-1ad4330c-50f7-11e7-81c9-270f721d3c0e.png)

**Comment by whikloj** [comment] 2017-06-14 17:41
@Natkeeran did you save between steps 2 and 3? I have not been able to replicate this, but I'm not sure I am following the steps correctly.

**Comment by whikloj** [comment] 2017-06-14 17:43
@Natkeeran also what is the commit you are referencing from? I can't find that commit in `islandora_image`

**Comment by MarcusBarnes** [comment] 2017-06-14 18:07
I've been able to reproduce afterall.   First make sure you create a collection.  Then create a Islandora Image via "Add content".   The initial message under the OBJ section is "Allowed types: png gif jpg jpeg tiff tif jp2 bmp."  Under "2M limit".  After refresh the message says "Allowed types: jp2."  Trying to add a .tiff file under 2MB after the refresh fails.

**Comment by whikloj** [comment] 2017-06-14 18:14
@MarcusBarnes ok so you:
1. Create an Islandora Collection
1. Fill out the title and save/publish the collection.
1. Create the Islandora Image
1. You don't need to populate any fields in the Islandora Image, or you do?
1. You don't save the Islandora Image, or you do?
1. Hit the browser refresh button and then the OBJ media field allowed extension changes?

Is that correct?

**Comment by Natkeeran** [comment] 2017-06-14 18:16
@whikloj That's the claw vagrant commit.  Below is the islandora_image commit.

```
commit e0fab4a794f4a52cccadad3b3a04de95a43e192f
Author: dannylamb <dlamb@islandora.ca>
Date:   Thu Jun 1 08:37:06 2017 -0300

    Images using nodes (#14)
```

**Comment by MarcusBarnes** [comment] 2017-06-14 18:19
@whikloj You should see the change to the OBJ section of the form by reloading the page in your browser before saving.   It's hard to see, but then if you try to add other file types (such as .tiff or .png in @Natkeeran  case) under the size limit, you get an error message.

**Comment by whikloj** [comment] 2017-06-14 18:23
@Natkeeran @MarcusBarnes thanks, ok I'll see if I can replicate it too.

**Comment by Natkeeran** [comment] 2017-06-14 19:05
@whikloj Possibly related.  After vagrant halt and up, activemq does not seem to start up (i.e http://localhost.com:8161/admin/ not available).  Thus, when creating new objects, 'Could not connect to a broker (Host: localhost)' error gets thrown.

**Comment by whikloj** [comment] 2017-06-14 20:39
@Natkeeran not sure if that is related. I think the issue is around the ajax calls. Here is how I messed it up.

1. I clicked Create Media on OBJ.
2. I clicked Create Media on JP2.
3. I started to upload a large (39MB) JP2 to the JP2 entity. (I upped the max file size to 2GB)
4. I clicked Cancel on the OBJ.

The OBJ seemingly should cancel quickly, but instead it hangs around until the JP2 ajax request is completed and the reason is......

![claw_inline_error](https://user-images.githubusercontent.com/2857697/27153557-8c23a0f4-5117-11e7-93af-e31e287a7027.jpg)

Looks like it is mixing up the various media_entities. This is probably a problem with the inline_media_entity module

**Comment by whikloj** [comment] 2017-06-14 20:46
Just to make it absolutely clear it has returned to the wrong location, I clicked **Remove** on the top one and **Create media** on the second one and got.

![claw_inline_error2](https://user-images.githubusercontent.com/2857697/27153872-aab8cfb6-5118-11e7-8bbc-1f75be00e183.jpg)

**Comment by dannylamb** [comment] 2018-09-06 14:27
Resolved via https://github.com/Islandora-CLAW/islandora/commit/a1987aecb747b0b297176fc4d34afdc22cbddb4d

**Closed by dannylamb** 2018-09-06 14:27 UTC
Labels: bug
