### ISSUE TITLE
Delete media entities with the "resource"

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#627] opened 2017-05-15 18:55 UTC
Placeholder for later..

We need to delete media_entities when we delete the "islandora_image" object. Currently they seems to be left orphaned. Perhaps this was a conscious decision, if not they should probably get dumped.

**Comment by whikloj** [comment] 2017-05-15 19:10
Also should we delete the NonRdfSource drupal object if we delete the Media Entity? Currently you can delete the media entity and the "object" remains.

**Comment by dannylamb** [comment] 2018-09-06 16:17
Duplicate of https://github.com/Islandora-CLAW/CLAW/issues/909

**Closed by dannylamb** 2018-09-06 16:18 UTC
